#!/bin/sh

if [ $(uname -n) = "Mobile-Box" ]; then
    capacity="$(cat "/sys/class/power_supply/BAT1/capacity")"

    # To preserver long term battery, it stops charging at 85% full
    # battery symbols are adjusgested to reflect that
    case 1 in
        $(($capacity >= 64)) ) 
            printf "  %d%%\n" $capacity ;;
        $(($capacity >= 43)) ) 
            printf " %d%%\n" $capacity ;;
        $(($capacity >= 22)) ) 
            printf " %d%%\n" $capacity ;;
        $(($capacity >= 10)) ) 
            printf " %d%%\n" $capacity ;;
        * ) 
            printf " %d%%\n" $capacity ;;
    esac
fi
