#!/bin/sh

if [ $(uname -n) = "Mobile-Box" ]; then
    capacity="$(cat "/sys/class/power_supply/BAT1/capacity")"

    case 1 in
        $(($capacity >= 75)) ) 
            printf "  %d%%\n" $capacity ;;
        $(($capacity >= 50)) ) 
            printf " %d%%\n" $capacity ;;
        $(($capacity >= 25)) ) 
            printf " %d%%\n" $capacity ;;
        $(($capacity >= 10)) ) 
            printf " %d%%\n" $capacity ;;
        * ) 
            printf " %d%%\n" $capacity ;;
    esac
fi
