#!/bin/sh

vol="$(wpctl get-volume @DEFAULT_AUDIO_SINK@)"

# If muted, print  and exit.
[ "$vol" != "${vol%\[MUTED\]}" ] && echo " Mute" && exit

vol="${vol#Volume: }"

split() {
	# For ommiting the . without calling and external program.
	IFS=$2
	set -- $1
	printf '%s' "$@"
}

vol="$(printf "%.0f" "$(split "$vol" ".")")"

case 1 in
	$((vol >= 50)) ) 
        printf " %d%%\n" $vol ;;
	$((vol >= 1)) ) 
        printf " %d%%\n" $vol ;;
	* ) 
        echo " Mute"  && exit ;;
esac
